import { Inter } from 'next/font/google';
import './globals.css';
import 'bootstrap/dist/css/bootstrap.min.css';
import Footer from '@/components/Footer';
import NavBar from '@/components/Navbar';
import EyeTrackingWrapper from '@/components/EyeTrackingWrapper';
import Providers from './providers';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Next.js Application Template',
  description: 'Generated by ics-software-engineering.github.io',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const classString = `${inter.className} wrapper`;
  return (
    <html lang="en">
      <head>
        {/* Add WebGazer.js Script via CDN */}
        <script src="https://webgazer.cs.brown.edu/webgazer.js" async />
      </head>
      <body className={classString}>
        <Providers>
          <NavBar />
          {/* EyeTracking component to track gaze */}
          <EyeTrackingWrapper />
          {children}
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
